/**
 * Bairros e setores de cada cidade, para sugerir no campo "bairro"
 * (a pessoa pode digitar qualquer outro).
 *
 * Fonte: OpenStreetMap (© colaboradores do OpenStreetMap, licença ODbL),
 * lugares marcados como bairro/setor dentro de cada município, revisados à mão.
 * Para acrescentar um bairro, é só pôr na lista da cidade.
 */
import type { Cidade } from "./constantes";

export const BAIRROS: Record<Cidade, readonly string[]> = {
  "Goiânia": [
    "Aeroviário",
    "Água Branca",
    "Aldeia do Vale",
    "Alpes",
    "Alphaville Flamboyant Residencial Araguaia",
    "Alphaville Residencial",
    "Alto da Glória",
    "Araguaia Park",
    "Bairro Boa Vista",
    "Bairro da Vitória",
    "Bairro Feliz",
    "Bairro Floresta",
    "Bairro Santo Hilário",
    "Bairro São Carlos",
    "Bairro São Domingos",
    "Cachoeira Dourada",
    "Capuava",
    "Celina Park",
    "Chácara Bom Retiro",
    "Chácara de Recreio São Joaquim",
    "Chácara do Governador",
    "Chácara Helou",
    "Chácara Mansões Rosa de Ouro",
    "Chácara Maria Dilce",
    "Chácara Retiro",
    "Chácara Rio Branco",
    "Chácaras Alto da Glória",
    "Chácaras Anhanguera",
    "Chácaras Botafogo",
    "Chácaras Califórnia",
    "Chácaras Cidade Pompeu",
    "Chácaras Elísios Campos",
    "Chácaras Nossa Senhora da Piedade",
    "Chácaras Recreio São João",
    "Chácaras Samambaia",
    "Chácaras Santa Bárbara",
    "Chácaras São Francisco de Assis",
    "Chácaras São José",
    "Chácaras Shangry-la",
    "Cidade Jardim",
    "Colônia Santa Marta",
    "Condomínio Anhanguera",
    "Condomínio Dakota",
    "Condomínio Jacarandá",
    "Condomínio Reserva San Marino",
    "Condomínio Rio Branco",
    "Condomínio Samambaia",
    "Conjunto Anhanguera",
    "Conjunto Caiçara",
    "Conjunto Cidade Universitária",
    "Conjunto Fabiana",
    "Conjunto Habitacional Aruanã I",
    "Conjunto Habitacional Aruanã II",
    "Conjunto Habitacional Madre Germana II",
    "Conjunto Palmares",
    "Conjunto Parque dos Eucaliptos",
    "Conjunto Primavera",
    "Conjunto Residencial Aruanã III",
    "Conjunto Residencial Campus",
    "Conjunto Residencial Paulo Pacheco",
    "Conjunto Riviera",
    "Conjunto Vera Cruz",
    "Delta Village",
    "Elísio Campos",
    "Esplanada do Anicuns",
    "Estância Vargem Bonita",
    "Faiçalville",
    "Fazenda Petrópolis - Residencial Monte Verde",
    "Granja Cruzeiro do Sul",
    "Ipiranga",
    "Jardim Abaporu",
    "Jardim América",
    "Jardim Ana Lúcia",
    "Jardim Aritana",
    "Jardim Atlântico",
    "Jardim Balneário Meia Ponte",
    "Jardim Barcelona",
    "Jardim Bela Vista",
    "Jardim Bom Jesus",
    "Jardim Botânico",
    "Jardim Brasil",
    "Jardim Califórnia",
    "Jardim Califórnia Parque Industrial",
    "Jardim Caravelas",
    "Jardim Clarissa",
    "Jardim Colorado",
    "Jardim Colorado Sul",
    "Jardim Conquista",
    "Jardim Corte Real",
    "Jardim Curitiba",
    "Jardim da Luz",
    "Jardim das Aroeiras",
    "Jardim das Esmeraldas",
    "Jardim das Hortências",
    "Jardim Diamantina",
    "Jardim Dom Fernando I",
    "Jardim Dom Fernando II",
    "Jardim Eli Forte Complemento",
    "Jardim Europa",
    "Jardim Florença",
    "Jardim Fonte Nova",
    "Jardim Gardênia",
    "Jardim Goiás",
    "Jardim Gramado",
    "Jardim Guanabara",
    "Jardim Guanabara II",
    "Jardim Guanabara III",
    "Jardim Guanabara IV",
    "Jardim Ipê",
    "Jardim Lageado",
    "Jardim Lago Azul",
    "Jardim Liberdade",
    "Jardim Maria Helena",
    "Jardim Mariliza",
    "Jardim Marques de Abreu",
    "Jardim Nova Esperança",
    "Jardim Novo Mundo",
    "Jardim Novo Mundo Extensão",
    "Jardim Novo Mundo II",
    "Jardim Novo Petrópolis",
    "Jardim Petrópolis",
    "Jardim Planalto",
    "Jardim Presidente",
    "Jardim Santa Cecília",
    "Jardim São José",
    "Jardim São Judas Tadeu",
    "Jardim Vista Bela",
    "Jardim Vitória II",
    "Jardins Lisboa",
    "Jardins Madri Complemento",
    "Lorena Park",
    "Loteamento Aruanã Park",
    "Loteamento Estâncias Vista Alegre",
    "Loteamento Grande Retiro",
    "Loteamento Granjas Brasil",
    "Loteamento Mansões Goianas",
    "Loteamento Privé Elza Fronza",
    "Loteamento Recanto Barravento",
    "Loteamento Recreio Panorama",
    "Loteamento Tropical Verde",
    "Loteamento Tupynambá dos Reis",
    "Maria Rosa",
    "Morada dos Sonhos",
    "Negrão de Lima",
    "Nova Suíça",
    "Osvaldo Rosa",
    "Panorama Parque",
    "Park Lozandes",
    "Parque Acalanto",
    "Parque Aeronáutico Antônio Sebba Filho",
    "Parque Amazônia",
    "Parque Anhanguera",
    "Parque Atheneu",
    "Parque Balneário",
    "Parque das Amendoeiras",
    "Parque das Flores",
    "Parque das Nações",
    "Parque dos Cisnes",
    "Parque Eldorado Oeste",
    "Parque Eldorado Oeste Extensão",
    "Parque Flamboyant",
    "Parque Industrial de Goiânia",
    "Parque Industrial Paulista",
    "Parque Maracanã",
    "Parque Oeste Industrial",
    "Parque Paraíso",
    "Parque Santa Cruz",
    "Parque Santa Maria",
    "Parque Santa Rita",
    "Portal Santa Rita",
    "Residencial 14 Bis",
    "Residencial Alice Barbosa",
    "Residencial Alphaville Flamboyant",
    "Residencial Ana Clara",
    "Residencial Anglo",
    "Residencial Antônio Barbosa",
    "Residencial Antônio Carlos Pires",
    "Residencial Aruanã",
    "Residencial Atalaia",
    "Residencial Balneário",
    "Residencial Barravento",
    "Residencial Bela Goiânia",
    "Residencial Belo Horizonte",
    "Residencial Bertim Belchior I",
    "Residencial Bertim Belchior II",
    "Residencial Brisas da Mata",
    "Residencial Brisas do Cerrado",
    "Residencial Buena Vista I",
    "Residencial Buena Vista II",
    "Residencial Buena Vista III",
    "Residencial Buena Vista IV",
    "Residencial Carla Cristina",
    "Residencial Carlos de Freitas",
    "Residencial Cléa Borges",
    "Residencial Costa Paranhos",
    "Residencial das Acácias",
    "Residencial Della Penna",
    "Residencial dos Ipês",
    "Residencial Eldorado",
    "Residencial Elizene Santana",
    "Residencial Estrela Dalva",
    "Residencial Felicidade",
    "Residencial Fidélis",
    "Residencial Fonte das Águas",
    "Residencial Fortaleza",
    "Residencial Forteville",
    "Residencial Green Park",
    "Residencial Guanabara",
    "Residencial Guarema",
    "Residencial Hawai",
    "Residencial Hugo de Morais",
    "Residencial Humaitá",
    "Residencial Irisville",
    "Residencial Itália",
    "Residencial Itamaracá",
    "Residencial Jardim Belvedere",
    "Residencial Jardim Camargo",
    "Residencial Jardim Helou",
    "Residencial Jardins do Cerrado 1",
    "Residencial Jardins do Cerrado 2",
    "Residencial Jardins do Cerrado 3",
    "Residencial Jardins do Cerrado 4",
    "Residencial Jardins do Cerrado 6",
    "Residencial Jardins do Cerrado 7",
    "Residencial João Paulo II",
    "Residencial José Viandeli",
    "Residencial Junqueira",
    "Residencial Juscelino Kubitschek",
    "Residencial Licardino Ney",
    "Residencial Lírios do Campo",
    "Residencial Luana Park",
    "Residencial Lucy Pinheiro",
    "Residencial Mansões Paraíso",
    "Residencial Mar Del Plata",
    "Residencial Maratá",
    "Residencial Maria Lourença",
    "Residencial Maria Oliveira",
    "Residencial Maringá",
    "Residencial Mirante",
    "Residencial Monte Pascoal",
    "Residencial Montes Claros",
    "Residencial Morada do Bosque",
    "Residencial Morada do Ipê",
    "Residencial Morumbi",
    "Residencial Mundo Novo 2",
    "Residencial Mundo Novo 3",
    "Residencial Nossa Morada",
    "Residencial Nossa Senhora Auxiliadora",
    "Residencial Nova Aurora",
    "Residencial Olinda",
    "Residencial Orlando de Morais",
    "Residencial Ouro Preto",
    "Residencial Park Solar",
    "Residencial Parque Mendanha",
    "Residencial Paulo Estrela",
    "Residencial Petrópolis",
    "Residencial Portal do Oriente",
    "Residencial Porto Seguro",
    "Residencial Privê dos Girassóis",
    "Residencial Privé Itanhangá",
    "Residencial Privê Norte",
    "Residencial Real Conquista",
    "Residencial Recanto das Emas",
    "Residencial Recanto do Bosque",
    "Residencial Recanto dos Buritis",
    "Residencial Recreio Panorama",
    "Residencial Rio Jordão",
    "Residencial Rio Verde",
    "Residencial San Marino",
    "Residencial Santa Fé",
    "Residencial São Geraldo",
    "Residencial São Leopoldo",
    "Residencial Senador Albino Boaventura",
    "Residencial Senador Paranhos",
    "Residencial Solar Ville",
    "Residencial Sonho Dourado",
    "Residencial Sonho Verde",
    "Residencial Vale da Serra",
    "Residencial Vale das Brisas",
    "Residencial Vale do Araguaia",
    "Residencial Vale dos Sonhos I",
    "Residencial Village Campos Verdes",
    "Residencial Village Santa Rita I",
    "Residencial Village Santa Rita II",
    "Residencial Village Santa Rita III",
    "Residencial Ytapuã",
    "Santa Genoveva",
    "São Carlos",
    "Serrinha",
    "Setor Aeroporto",
    "Setor Alto do Vale",
    "Setor Asa Branca",
    "Setor Bela Vista",
    "Setor Bueno",
    "Setor Campinas",
    "Setor Cândida de Morais",
    "Setor Castelo Branco",
    "Setor Central",
    "Setor Coimbra",
    "Setor Crimeia Leste",
    "Setor Crimeia Oeste",
    "Setor dos Afonsos",
    "Setor dos Funcionários",
    "Setor Empresarial",
    "Setor Estrela Dalva",
    "Setor Gentil Meirelles",
    "Setor Goiânia 2",
    "Setor Jaó",
    "Setor Leste Universitário",
    "Setor Leste Vila Nova",
    "Setor Marabá",
    "Setor Marista",
    "Setor Matinha",
    "Setor Morada do Sol",
    "Setor Morais",
    "Setor Negrão de Lima",
    "Setor Noroeste",
    "Setor Norte Ferroviário",
    "Setor Norte Ferroviário II",
    "Setor Nova Vila",
    "Setor Novo Horizonte",
    "Setor Novo Planalto",
    "Setor Oeste",
    "Setor Orientville",
    "Setor Parque Tremendão",
    "Setor Pedro Ludovico",
    "Setor Perim",
    "Setor Progresso",
    "Setor Recanto das Minas Gerais",
    "Setor Santa Genoveva",
    "Setor Santos Dumont",
    "Setor Solar Santa Rita",
    "Setor Sudoeste",
    "Setor Sul",
    "Setor Universitário",
    "Setor Urias Magalhães",
    "Sítio de Recreio Caraíbas",
    "Sítio de Recreio dos Bandeirantes",
    "Sítio de Recreio Ipê",
    "Sítio de Recreio Mansões do Campus",
    "Sítio de Recreio Pindorama",
    "Sítio de Recreio São Geraldo",
    "Sítio São Domingos",
    "Sítios de Recreio Paraíso Tropical",
    "Solange Parque I",
    "Solange Parque II",
    "Solange Parque III",
    "Vale dos Sonhos II",
    "Vila Abajá",
    "Vila Bandeirantes",
    "Vila Boa",
    "Vila Canaã",
    "Vila Clemente",
    "Vila Colemar Natal e Silva",
    "Vila Concórdia",
    "Vila Cristina",
    "Vila Divino Pai Eterno",
    "Vila Finsocial",
    "Vila Froes",
    "Vila Itatiaia",
    "Vila Jaraguá",
    "Vila Jardim Pompéia",
    "Vila Jardim Vitória",
    "Vila João Vaz",
    "Vila Maria Dilce",
    "Vila Maria José",
    "Vila Maria Luíza",
    "Vila Mariana",
    "Vila Martins",
    "Vila Matilde",
    "Vila Mauá",
    "Vila Megale",
    "Vila Militar",
    "Vila Monticelli",
    "Vila Morais",
    "Vila Mutirão",
    "Vila Mutirão I",
    "Vila Mutirão II",
    "Vila Nossa Senhora Aparecida",
    "Vila Nova",
    "Vila Osvaldo Rosa",
    "Vila Pedroso",
    "Vila Redenção",
    "Vila Regina",
    "Vila Rizzo",
    "Vila Romana",
    "Vila Roriz",
    "Vila Rosa",
    "Vila Santa Cruz",
    "Vila Santa Helena",
    "Vila Santa Isabel",
    "Vila Santa Maria",
    "Vila São João",
    "Vila União",
    "Vila Viana",
    "Village Atalaia",
    "Village Casa Grande",
    "Village Santa Rita",
    "Ville de France",
    "Zona Industrial Pedro Abrão",
  ],
  "Aparecida de Goiânia": [
    "Águas Claras",
    "Alvorada Oeste",
    "Alvorada Sul",
    "American Park",
    "Aparecida Garden",
    "Bairro Cardoso",
    "Bairro Cardoso 2",
    "Bairro Ilda",
    "Chácaras Santa Luzia",
    "Cidade Empresarial",
    "Cidade Livre",
    "Cidade Satélite São Luiz",
    "Cidade Vera Cruz",
    "Colina Azul",
    "Colinas de Homero",
    "Conjunto Cruzeiro do Sul",
    "Conjunto Habitacional Madre Germana",
    "Conjunto Residencial Storil",
    "Conjunto Santa Fé",
    "Expansul",
    "Goiânia Park Sul",
    "Granjas Reunidas Nossa Senhora de Lourdes",
    "Independência",
    "Independência Setor das Mansões",
    "Industrial Santo Antônio",
    "Itapoã",
    "Jardim Bela Morada",
    "Jardim Belo Horizonte",
    "Jardim Boa Esperança",
    "Jardim Canadá",
    "Jardim Cascatas",
    "Jardim Cristal",
    "Jardim das Acácias",
    "Jardim das Esmeraldas",
    "Jardim das Hortências",
    "Jardim Dom Bosco",
    "Jardim dos Girassóis",
    "Jardim Esplanada",
    "Jardim Florença",
    "Jardim Helvécia",
    "Jardim Imperial",
    "Jardim Ipê",
    "Jardim Ipiranga",
    "Jardim Iracema",
    "Jardim Isaura",
    "Jardim Luz",
    "Jardim Maranata",
    "Jardim Maria Inês",
    "Jardim Miramar",
    "Jardim Mont Serrat",
    "Jardim Monte Cristo",
    "Jardim Nova Era",
    "Jardim Olímpico",
    "Jardim Palacius",
    "Jardim Paraíso",
    "Jardim Rio Dourado",
    "Jardim Rio Grande",
    "Jardim Riviera",
    "Jardim Rosa do Sul",
    "Jardim Santo Antônio",
    "Jardim São Conrado",
    "Jardim Tiradentes",
    "Jardim Tropical",
    "Jardim Veneza",
    "Jardins Mônaco",
    "Jardins Viena",
    "Mansões Paraíso",
    "Morada dos Pássaros",
    "Nova Cidade",
    "Nova Olinda",
    "Papillon Park",
    "Parque Atalaia",
    "Parque das Nações",
    "Parque Floresta",
    "Parque Hayala",
    "Parque Ibirapuera",
    "Parque Industrial Araguaia",
    "Parque Itamaraty",
    "Parque Itatiaia",
    "Parque Montreal",
    "Parque Primavera",
    "Parque Rio das Pedras",
    "Parque Santa Cecília",
    "Parque Trindade",
    "Parque Veiga Jardim",
    "Polo Empresarial Goiás",
    "Pontal Sul",
    "Porto das Pedras",
    "Quinta da Boa Vista",
    "Residencial Alvaluz",
    "Residencial Andrade Reis",
    "Residencial Araguaia",
    "Residencial Brasicon",
    "Residencial Cândido de Queiroz",
    "Residencial Caraíbas",
    "Residencial Maria Luiza",
    "Residencial Norte-Sul",
    "Residencial Pôr do Sol",
    "Residencial Santa Fé",
    "Residencial Village Garavelo",
    "Retiro do Bosque",
    "Riviera Sul",
    "Rosa dos Ventos",
    "Setor Ana Rosa",
    "Setor Araguaia",
    "Setor Central",
    "Setor Colonial Sul",
    "Setor Comendador Walmor",
    "Setor Conde dos Arcos",
    "Setor dos Afonsos",
    "Setor dos Estados",
    "Setor Fabrício",
    "Setor Garavelo",
    "Setor Marista Sul",
    "Setor Ocidente da Vila Brasília",
    "Setor Oeste",
    "Setor Residencial Campos Elísios",
    "Setor Rio Vermelho",
    "Setor Santo André",
    "Setor Santos Dumont",
    "Setor Serra Dourada",
    "Solar das Candeias",
    "Terra Prometida",
    "Vera Cruz",
    "Vila Adélia",
    "Vila Alzira",
    "Vila Brasília",
    "Vila Delfiori",
    "Vila Irmãos Souza",
    "Vila Maria",
    "Vila Mariana",
    "Vila Oliveira",
    "Vila Santos Dumont",
    "Vila São Manoel",
    "Vila Sul",
    "Villa Romana",
    "Virgínia Parque",
  ],
  "Senador Canedo": [
    "Alphaville Senador Canedo",
    "Bairro Alvorada",
    "Bairro das Indústrias",
    "Bairro Polo Empresarial Maria Pires Perillo",
    "Bairro São Francisco",
    "Bairro São Francisco II",
    "Chácaras São Geraldo",
    "Chácaras Vargem Bonita",
    "Condomínio Alta Vista",
    "Condomínio Alto da Boa Vista",
    "Condomínio Ecológico Mansões Morumbi",
    "Condomínio Portugal",
    "Condomínio Tovolândia",
    "Conjunto Habitacional Dona Lindu",
    "Conjunto Habitacional Jardim Sabiá",
    "Conjunto Habitacional Nova Morada",
    "Conjunto Margarida Procópio",
    "Conjunto Morada do Morro",
    "Conjunto Uirapuru",
    "Distrito Agroindustrial de Senador Canedo",
    "Estância Vargem Bonita",
    "Industrial Estrela do Sul",
    "Jardim Bougainville",
    "Jardim das Oliveiras",
    "Jardim do Lago",
    "Jardim Flamboyant",
    "Jardim Imperial",
    "Jardim Ingá",
    "Jardim Liberdade",
    "Jardim Nova Goiânia",
    "Jardim Primavera",
    "Jardim Sevilha",
    "Jardim Todos os Santos",
    "Jardins Barcelona",
    "Jardins Bolonha",
    "Jardins Capri",
    "Jardins Nápoles",
    "Jardins Parma",
    "Jardins Porto",
    "Parque Alvorada",
    "Parque Industrial Senador Canedo",
    "Parque Residencial Morumbi",
    "Polo Confeccionista Senador Canedo",
    "Polo Educacional e Cultural",
    "Polo Empresarial Monte Horebe",
    "Polo Empresarial Nova Canaã",
    "Recanto dos Sonhos",
    "Reserva do Bosque Condomínio Clube",
    "Residencial Anuar Auad",
    "Residencial Aracy Amaral",
    "Residencial Aurora das Mansões",
    "Residencial Boa Esperança",
    "Residencial Boa Vista",
    "Residencial Buriti",
    "Residencial Campo Belo",
    "Residencial Entre Lagos",
    "Residencial Flor do Ipê",
    "Residencial Gênova",
    "Residencial Hebrom",
    "Residencial Jardim Canedo",
    "Residencial Jardim Veneza",
    "Residencial Laranjeiras",
    "Residencial Marília",
    "Residencial Morada do Bosque",
    "Residencial Morada do Sol",
    "Residencial Paraíso",
    "Residencial Parque das Flores",
    "Residencial Parque dos Buritis",
    "Residencial Pedro Miranda",
    "Residencial Porto Seguro",
    "Residencial Prado",
    "Residencial Ravena",
    "Residencial Recanto das Oliveiras",
    "Residencial Rio Araguaia",
    "Residencial Riviera do Retiro",
    "Residencial Santa Edwiges",
    "Residencial Solar das Oliveiras",
    "Residencial Vale Verde",
    "Residencial Vila Verde",
    "Residencial Village dos Buritis",
    "Residencial Zélia Nunes",
    "Setor Castros",
    "Setor Central",
    "Setor Comercial",
    "Setor Estrela do Sul",
    "Setor Genoveva Rezende Machado",
    "Setor Matinha",
    "Setor Monte Azul",
    "Setor Morada Nova",
    "Setor Park Vitória",
    "Setor Vargem Bonita",
    "Sítios Boa Sorte",
    "Sítios de Recreio Solar das Auroras",
    "Sítios Mansões Retiro",
    "Sítios Olhos D'Água",
    "Sítios Vale das Brisas",
    "Solar Monte Cristo",
    "Solar Park Ilhabela",
    "Terrabela Cerrado",
    "Terrass Alpha Residencial",
    "Top do Parque",
    "Vila Bonsucesso",
    "Vila Galvão",
    "Vila São João",
    "Vila São Sebastião",
  ],
  "Trindade": [
    "Centro",
    "Jardim Alto do Cerrado",
    "Jardim Imperial",
    "Residencial Marise",
    "Residencial Nova Morada",
    "São Bernardo",
    "Setor Bela Vista",
    "Setor Cristina",
    "Setor Mariápolis",
    "Vila Pai Eterno",
  ],
  "Goianira": [
    "Centro",
    "Chácara São Domingos",
    "Conjunto Primavera",
    "Fonte das Águas",
    "Goyazes",
    "Jardim das Margaridas",
    "Jardim Imperial",
    "Parque Maracanã",
    "Recanto Sonhado",
    "Residencial Araguaia",
    "Residencial Arco do Triunfo",
    "Residencial Flora Nogueira",
    "Residencial Florença",
    "Residencial Limoeiro",
    "Residencial Los Angeles",
    "Residencial Montreal",
    "Residencial Paranaíba",
    "Residencial Parque dos Girassóis",
    "Residencial Planalto",
    "Residencial Tocantins",
    "Residencial Triunfo",
    "São Francisco",
    "Serra Dourada",
    "Setor Cora Coralina",
    "Setor Delta",
    "Setor Sul",
    "Solar das Paineiras",
    "Vila Adilair",
    "Vila Isabel",
  ],
  "Nerópolis": [
    "Centro",
  ],
  "Hidrolândia": [
    "Aldeia dos Sonhos",
    "Bairro Nazaré",
    "Betânia",
    "Centro",
    "Conceição",
    "Condomínio Águas da Serra",
    "Condomínio Vale dos Lírios",
    "Copacabana",
    "Estrela do Sul",
    "Garavelo Sul",
    "Irajá",
    "Jardim Adelaide",
    "Jardim Primavera",
    "Nova Fátima",
    "Portal das Águas",
    "Residencial Dolce Vita",
    "Rosa dos Ventos",
    "Sítios de Recreio Savannah",
    "Vale Azul",
    "Vila Mutirão",
    "Village dos Ipês",
  ],
  "Bela Vista de Goiás": [
    "Armando Antônio",
    "Buritizais",
    "Centro",
    "Condomínio das Palmeiras",
    "Condomínio Recanto dos Ipês",
    "Conjunto Habitacional Bela Vista",
    "Dona Clotildes",
    "Dona Delfina",
    "Jardim Alphaville",
    "Jardim Barcelona",
    "Jardim das Palmeiras",
    "Jardim Flamboyant",
    "Jardim Primavera",
    "Lúcia Alice",
    "Maria Nadir",
    "Parque dos Buritis",
    "Parque Las Vegas",
    "Pérola do Sul",
    "Portal do Sul",
    "Recanto da Mata",
    "Residencial Sussuapara",
    "Residencial Via Flores",
    "Residencial Vitória",
    "Santa Cruz",
    "Santo Antônio",
    "São Geraldo",
    "Setor Dona Benedita",
    "Setor Oeste",
    "Setor São Jorge",
    "Ulisses Guimarães",
    "Vila Flores",
    "Vila São Vicente",
  ],
  "Abadia de Goiás": [
    "Centro",
    "Daniella Park",
    "Goiânia Sul Residencial",
    "Residencial Dori",
    "Residencial Ipanema",
    "Residencial Jair Ferreira",
    "Residencial Maria Oliveira",
    "Residencial Paineiras",
    "Residencial Porto Seguro",
    "Vila João Custódio",
  ],
  "Aragoiânia": [
    "Cachoeirinha",
    "Centro",
    "Jardim das Flores",
    "Jardim Imperial",
    "Jardim Ipê",
    "Parque das Acácias",
    "Setor Bela Vista",
  ],
  "Bonfinópolis": [
    "Alto da Boa Vista",
    "Campos Dourados",
    "Centro",
    "Estação Central",
    "Jardim Ana Amélia",
    "Jardim Santana",
    "Residencial Campo Belo",
    "Residencial Cristal",
    "Residencial Walter Paulo",
    "Setor Juliana",
    "Vila São José",
  ],
  "Brazabrantes": [
    "Centro",
  ],
  "Caldazinha": [
    "Centro",
  ],
  "Caturaí": [
    "Centro",
  ],
  "Goianápolis": [
    "Centro",
  ],
  "Guapó": [
    "Centro",
    "Cidade Nova",
    "Condomínio Recanto Paraíso",
    "Condomínio Talismã",
    "David Barbosa",
    "Jardim Imperial",
    "Jardim Primavera",
    "Loteamento Vale do Sol",
    "Posselândia",
    "Recanto da Serra",
    "Residencial Bandeiras",
    "Residencial Buritis",
    "Residencial Dona Alice",
    "Residencial Sol Nascente",
    "Setor Oeste",
    "Setor Progresso",
    "Setor Sul",
    "Setor Vila Boa",
    "Vale dos Sonhos",
    "Vila João Pedro",
    "Vila João Rassi",
    "Vila Lagoa",
    "Vila Luciene",
  ],
  "Inhumas": [
    "Centro",
  ],
  "Nova Veneza": [
    "Bortolotto",
    "Bortoluzzi",
    "Centro",
    "Elisa",
    "Nossa Senhora do Caravaggio",
  ],
  "Santo Antônio de Goiás": [
    "Centro",
    "Condomínio Residencial Califórnia",
    "Loteamento Nelson Barnabé",
    "Setor São Domingos",
    "Setor Sul",
    "Vila Campos",
    "Vila Estrela",
    "Vila Florença",
  ],
  "Terezópolis de Goiás": [
    "Centro",
  ],
};
